#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
	if (file_exists($file)) {
		define('DBUTIL_COMPOSER_AUTOLOAD', $file);
		break;
	}
}

if(defined('DBUTIL_COMPOSER_AUTOLOAD')) {
	require_once(DBUTIL_COMPOSER_AUTOLOAD);
} else {
	printf("you must run composer install first\n");
	exit;
}

use RavenTools\DbUtils\Schema;
use RavenTools\DbUtils\Server\Mysqld;
use RavenTools\DbUtils\PdoClient;

error_reporting(E_ALL ^ E_NOTICE);

$command = $argv[1];

$valid_commands = ["startdb","lint","bootstrap"];

switch($command) {
	default:
		printf("usage: %s [%s]\n",$argv[0],implode("|",$valid_commands));
		break;

	case "startdb":
		$db = new Mysqld;
		$db->start();
		break;

	case "lint":
		$path = $argv[2];

		// temporary mysqld for the schema lint
		$server = new Mysqld;
		$port = $server->start();

		$db = PdoClient::get([
			'host' => '127.0.0.1',
			'port' => $port,
			'user' => 'root'
		]);

		$schema = new Schema([
			'db' => $db,
			'path' => $path,
			'table_params' => [
				'truncate' => true
			]
		]);

		if($schema->lint() === false) {
			echo "lint failed\n";
			exit(1);
		}

		break;

	case "bootstrap":

		$path = $argv[2];
		$dsn = $argv[3];

		if(empty($dsn)) {
			echo "dsn argument required\n";
			exit(1);
		}
		$config = json_decode($dsn,true);

		$create_db = PdoClient::get([
			'name' => "create_db",
			'host' => $config['host'],
			'port' => $config['port'],
			'user' => $config['user'],
			'password' => $config['password']
		]);
		$create_db->exec(sprintf(
			"DROP DATABASE `%s`; CREATE DATABASE `%s`",
			$config['dbname'],
			$config['dbname']
		));

		$db = PdoClient::get($config);

		$schema = new Schema([
			'db' => $db,
			'path' => $path
		]);

		$schema->create();

		break;
}
